# Generated by Django 2.2.3 on 2019-07-01 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=3)], verbose_name='Sales Tax'),
        ),
    ]
