# Generated by Django 2.2.3 on 2019-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190720_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='startup_route',
            field=models.CharField(choices=[('APP', '/app'), ('MY_LISTS', '/lists'), ('NULL', None)], default='BLANK', max_length=10, null=True, verbose_name='Default on Login'),
        ),
    ]
