# Generated by Django 2.2.3 on 2019-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_applicationuser_startup_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='startup_route',
            field=models.CharField(blank=True, choices=[('APP', '/app'), ('MY_LISTS', '/lists'), ('NULL', None)], default='BLANK', max_length=10, verbose_name='Default on Login'),
        ),
    ]
