# Generated by Django 2.2.4 on 2019-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190720_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='startup_route',
            field=models.CharField(blank=True, max_length=10, verbose_name='Default Route on Login'),
        ),
    ]
