# Generated by Django 2.2.3 on 2019-07-20 01:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, verbose_name='Item Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('store_name', models.CharField(max_length=110, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='List Grocery Store Name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
