# Generated by Django 2.2.3 on 2019-07-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Unit Price'),
            preserve_default=False,
        ),
    ]
