# Generated by Django 2.2.2 on 2019-06-11 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20190604_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='UPC',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='upc',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='UPC'),
        ),
    ]
