# Generated by Django 2.2.5 on 2019-09-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_groceryitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='store_name',
        ),
    ]
