# Generated by Django 2.2.3 on 2019-07-17 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_groceryitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Store Name'),
        ),
    ]
