# Generated by Django 2.2.3 on 2019-07-17 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_groceryitem_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='upc',
            field=models.CharField(blank=True, editable=False, max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='UPC'),
        ),
    ]
