export const TRIGGER_LOAD_ANIMATION = "TRIGGER_LOAD_ANIMATION";
export const TURN_OFF_LOAD_ANIMATION = "TURN_OFF_LOAD_ANIMATION";

export const POST_USER_REGISTRATION = "POST_USER_REGISTRATION";

export const POST_USER_LOGIN = "POST_USER_LOGIN";
export const POST_USER_LOGOUT = "POST_USER_LOGOUT";

export const SET_USER_DEFAULT_PAGE = "SET_USER_DEFAULT_PAGE";
