# Generated by Django 2.2.2 on 2019-06-04 04:41

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Sales Tax')),
                ('total_items', models.IntegerField(verbose_name='Total Items')),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='Items.GroceryItem', verbose_name='Grocery Items')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
