# Generated by Django 2.2.2 on 2019-06-28 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitemlist',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
