# Generated by Django 2.2.3 on 2019-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitemlist',
            name='amount_budgeted',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=100, verbose_name='Amount Budgeted'),
            preserve_default=False,
        ),
    ]
